[package]
name = "automated-rust-releases"
version = "0.1.0"
description = "https://blog.orhun.dev/automated-rust-releases"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
